lir:
  satellite_image_name: "satellite"
  num_of_orbit: 2
  sat_per_orbit: 11
  default_bloom_filter_length: 32
  default_hash_seed: 18
  default_number_of_hash_funcs: 5
  listening_port: 30000
  abs_dir_of_projects: /home/zhf/Projects/lir
  relative_dir_of_frr: lir_emulator/resources/routing/frr
  relative_dir_of_lir_identifiers: lir_emulator/resources/routing/lir/identifiers
  relative_dir_of_lir_routes: lir_emulator/resources/routing/lir/routes
  relative_dir_of_id_to_ip_mapping: lir_emulator/resources/network
  relative_dir_of_images_manager: lir_emulator/src/docker/images/build_docker_images/bin
  frr_enabled: true
  lir_enabled: true